from app.orchestration.rule_based_intent_router import IntentRule

SERVICES_CATALOG_ROUTING_RULES = (
    IntentRule(
        "services_catalog",
        "services.detail",
        (
            "cuánto cuesta",
            "cuanto cuesta",
            "cuánto vale",
            "cuanto vale",
            "cuánto sale",
            "cuanto sale",
            "qué precio",
            "que precio",
            "precio de",
            "valor de",
            "cuánto dura",
            "cuanto dura",
            "duración de",
            "duracion de",
        ),
    ),
    IntentRule(
        "services_catalog",
        "services.list",
        (
            "qué servicios ofrecen",
            "que servicios ofrecen",
            "cuáles servicios",
            "cuales servicios",
            "lista de servicios",
            "servicios disponibles",
            "que servicios tienen",
            "qué servicios tienen",
            "qué servicios manejan",
            "que servicios manejan",
            "qué manejan",
            "que manejan",
            "qué servicios hay",
            "que servicios hay",
            "qué hacen",
            "que hacen",
            "qué atienden",
            "que atienden",
            "qué me pueden ofrecer",
            "que me pueden ofrecer",
        ),
    ),
    IntentRule(
        "services_catalog",
        "services.search",
        (
            "tienen servicio",
            "ofrecen servicio",
            "tienen consulta",
            "ofrecen consulta",
            "hay servicio de",
            "servicio de",
            "manejan servicio de",
            "manejan consulta de",
            "hacen servicio de",
            "hacen consulta de",
            "atienden servicio de",
            "atienden consulta de",
        ),
    ),
)
